name: iris-feature-pipeline-daily

on:
  workflow_dispatch:
  schedule:
    - cron: '00 21 * * *'

jobs:
  test_schedule:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo content
        uses: actions/checkout@v2

      - name: setup python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10.10'
          
      - name: install python packages
        run: |
          python -m pip install --upgrade pip
          pip install -r ./lab1/requirements.txt
          
      - name: execute python workflows from bash script
        env: 
          HOPSWORKS_API_KEY: ${{ secrets.HOPSWORKS_API_KEY }}
        run: ./lab1/wine/wine-feature-pipeline-daily.py
